### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by nilsbecker** [Octachron/tensority#1]
i cloned the repository locally and then tried `opam pin add tensority/`. i keep getting package not found errors. first: Package topkg not found; then after manually installing Topkg, i get Package ppx_indexop not found. somehow opam does not know it needs to resolve dependencies? am i doing it wrong?

**Comment by Octachron** [comment]
I should clearly improve the installation process. The package `ppx_indexop` is a build-only dependency that comes from https://github.com/Octachron/ppx_indexop, pinning the repository with opam should work.

**Comment by nilsbecker** [comment]
ok it did work, thanks. just fyi: tensority names itself tensority-  (with a dash)

**Comment by Octachron** [comment]
Good point, the dash was a forgotten remnant of a previous name. Fixed.

**Comment by nilsbecker** [comment]
i was able to `#require tensority` and `tensority.ppx` now but i get Dimension_error when trying the first lines of the example in the README. i opened the packages and copy-pasted the literal definition of array4. (in utop). i also tried the non-ppx example in the README which also gave similar errors. is the README out of date?

**Comment by Octachron** [comment]
Sorry, there was some significant bit rot after recent refactoring. I have fixed the problem in the few last commits, the example should at least works now (and I really need to write tests).

**Comment by Octachron** [comment]
The `ppx_indexops` ppx has been replaced by custom index operators, the tests run; installation should be doable if not recommended.
